#!/bin/bash

HASH=$(cat "$HOME/.cache/clipmenu/hash")

entries=""
ls -t ~/.cache/clipmenu/* 2>/dev/null | grep -v hash | while read -r f; do
    case "$f" in
        *thumb_*.png) 
            echo "$HASH$f"
            ;;
        *.txt) 
            echo "$(cat "$f" | sed -z 's/\\/\\\\/g' | sed -z 's/\n/\\n/g')"
            ;;
    esac
done | {
    cat
    for i in $(seq 10); do echo " "; done
} | dmenu -l 10 -p "clip" -is 120 -ip "$HASH" -w "$(xdotool getactivewindow)" | {

read -r sel

[ -z "$sel" ] && exit

if [[ "$sel" == ${HASH}* ]]; then
    thumb="${sel#$HASH}"
    base="${thumb/thumb_/full_}"
    full="$(ls ${base%.*}.*)"
    ext="${full##*.}"
    xclip -selection clipboard -t image/"$ext" < "$full"
    rm -f "$thumb" "$full"
else
    echo -e -n "$sel" | xclip -selection clipboard
fi

}
